---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: latest
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

- name: print env
  image: felixboehm/drone-env
  pull: true

